// The documents the public demo will run, and nothing else. The id is the only thing a
// visitor can send, and it is looked up in this table, so no request can name a path.
//
// All six are synthetic fixtures generated by scripts/make-fixtures.ts. The companies do
// not exist and none of the tax IDs is a valid VAT number (see README, "Grenzen").
export interface DemoDocument {
  id: string;
  label: string;
  /** What a visitor is looking at, in plain words. Never a filesystem path. */
  kind: string;
  /** Why this document is in the set: the thing it makes visible. */
  note: string;
  contentType: string;
}

interface DemoDocumentSource extends DemoDocument {
  path: string;
}

const documents: DemoDocumentSource[] = [
  {
    id: "mustard-logistics-001",
    label: "MYL-2026-001",
    kind: "Born-digital PDF",
    note: "Carries a text layer, so no OCR runs and there is no OCR doubt to report.",
    contentType: "application/pdf",
    path: "corpus/mustard-logistics-001.pdf"
  },
  {
    id: "mustard-logistics-001-scan",
    label: "MYL-2026-001, scanned",
    kind: "Scanned image",
    note: "The same invoice as an image. Tesseract has to read it, and it is not sure everywhere.",
    contentType: "image/png",
    path: "corpus/mustard-logistics-001-scan.png"
  },
  {
    id: "northsea-parts-1042",
    label: "NSP-1042",
    kind: "Born-digital PDF",
    note: "Two line items, 22 percent tax.",
    contentType: "application/pdf",
    path: "corpus/northsea-parts-1042.pdf"
  },
  {
    id: "rhein-freight-778",
    label: "RFS-778",
    kind: "Born-digital PDF",
    note: "A single line item, no vendor address in the document.",
    contentType: "application/pdf",
    path: "corpus/rhein-freight-778.pdf"
  },
  {
    id: "baltic-coldchain-512",
    label: "BCC-512",
    kind: "Born-digital PDF",
    note: "Two line items, 21 percent tax.",
    contentType: "application/pdf",
    path: "corpus/baltic-coldchain-512.pdf"
  },
  {
    id: "alpine-spares-9201",
    label: "AS-9201",
    kind: "Born-digital PDF",
    note: "Priced in GBP, so the currency has to survive extraction.",
    contentType: "application/pdf",
    path: "corpus/alpine-spares-9201.pdf"
  }
];

/** The public list. Strips the path, which is the one field a visitor must never see. */
export function listDemoDocuments(): DemoDocument[] {
  return documents.map(({ path: _path, ...rest }) => rest);
}

export function findDemoDocument(id: unknown): DemoDocumentSource | undefined {
  return typeof id === "string" ? documents.find((document) => document.id === id) : undefined;
}
